const extensionToLanguageMap: { [key: string]: string } = {
  '.js': 'javascript',
  '.ts': 'typescript',
  '.html': 'html',
  '.css': 'css',
  '.scss': 'scss',
  '.json': 'json',
  '.md': 'markdown',
  '.py': 'python',
  '.java': 'java',
  '.c': 'c',
  '.cpp': 'cpp',
  '.cs': 'csharp',
  '.php': 'php',
  '.rb': 'ruby',
  '.rs': 'rust',
  '.go': 'go',
  '.swift': 'swift',
  '.sql': 'sql',
  '.xml': 'xml',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.sh': 'shell',
  '.bat': 'bat',
  '.pl': 'perl',
  '.r': 'r',
  '.vue': 'vue',
  '.jsx': 'javascript',
  '.tsx': 'typescript',
  '.lua': 'lua',
  '.dart': 'dart',
  '.kt': 'kotlin',
  '.m': 'objective-c',
  '.mm': 'objective-cpp',
  '.groovy': 'groovy',
}

export default extensionToLanguageMap
